### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by ainola** [hagabaka/hib-dlagent#11]
Thanks for making this!

I've noticed that there isn't any license associated with this project. Would you be open to possibly licensing under something that would enable distribution and modification, such as the GPL?

**Comment by ainola** [comment]
Thanks for such a quick turnaround! If I could annoy one last time... could you add a new release so that this can be packaged 'properly' without downloading a separate license that is technically not applicable for an older version?

**Comment by hagabaka** [comment]
~What do you mean by adding a new release?~ Added a new release. Also, I haven't used this for a long time. Does it still work?

**Comment by ainola** [comment]
It does, last I checked. Admittedly it's been a while since I've used it. It's a fairly popular package in the Archlinux AUR [1] and I haven't had anyone complain.

Thanks for the release and for your patience!

[1] https://aur.archlinux.org/packages/hib-dlagent/
