### ISSUE TITLE
Not working anymore, identification problem

### ISSUE THREAD

**Issue by mwestphal** [hagabaka/hib-dlagent#5]
Here is what i obtain when looking for any file in hib.
There is no window openning for any captcha.

[glow@GlowArch ~]$ /usr/bin/hib-dlagent -l -p pwd -u email@gmail.com -s Dustforce-Linux-2014-12-22.sh 

Fri Feb 20 2015 08:58:55 GMT+0100 (CET) Opening listing page...
Fri Feb 20 2015 08:58:57 GMT+0100 (CET) Opened listing page: success
Fri Feb 20 2015 08:58:57 GMT+0100 (CET) Entering login information...
Fri Feb 20 2015 08:58:57 GMT+0100 (CET) Submitting login information and/or captcha response...
Fri Feb 20 2015 08:58:58 GMT+0100 (CET) Entering login information...
Fri Feb 20 2015 08:58:58 GMT+0100 (CET) Submitting login information and/or captcha response...
Fri Feb 20 2015 08:58:59 GMT+0100 (CET) Entering login information...
Fri Feb 20 2015 08:58:59 GMT+0100 (CET) Submitting login information and/or captcha response...
Fri Feb 20 2015 08:58:59 GMT+0100 (CET) Entering login information...
Fri Feb 20 2015 08:58:59 GMT+0100 (CET) Submitting login information and/or captcha response...
Fri Feb 20 2015 08:59:00 GMT+0100 (CET) Entering login information...
Fri Feb 20 2015 08:59:00 GMT+0100 (CET) Submitting login information and/or captcha response...
Fri Feb 20 2015 08:59:01 GMT+0100 (CET) Entering login information...
Fri Feb 20 2015 08:59:01 GMT+0100 (CET) Submitting login information and/or captcha response...

**Comment by hagabaka** [comment]
Fixed by 13a1153d52347b769c71cdf0fdec37d91cc602af
