### ISSUE TITLE
hib-dlagent hang

### ISSUE THREAD

**Issue by Yamakaky** [hagabaka/hib-dlagent#7]
Hi
`hib-dlagent -u <user> -p <password> bla`
It doesn't do anything : 0% cpu use, no network trafic, no stdout output. Any idea ?
phantomjs-config.json:
```json
{
  "webSecurityEnabled": false,
  "ignoreSslErrors": true,
  "diskCacheEnabled": true,
}
```

**Comment by hagabaka** [comment]
Since  13a1153d52347b769c71cdf0fdec37d91cc602af (version 0.7) hib-dlagent doesn't use phantomjs, and `phantomjs-config.json` is not included any more. Have you updated?

**Comment by Yamakaky** [comment]
Sorry, I used a ancien package (v0.6) hib-dlagent-phantomjs, which doesn't even exist on archlinux ^^
Now, I have a "wrong passord" error. Mine includes a &, maybe an encoding error ?

**Comment by hagabaka** [comment]
I just changed my password to include & and tested, and I don't have this problem.

**Comment by Yamakaky** [comment]
Sorry, I share my account with a friend and he changed the email address ^^
